### ISSUE TITLE
大佬 麻烦看一下安建大适用不 java打包的整不明白=-=

### ISSUE THREAD

**Issue by fusang1337** [quarkape/ecnu-library-book#1]
http://219.231.8.77/web/index/area/1
http://219.231.8.77/web/area?area=21&segment=156122&day=2023-03-06&startTime=09:40&endTime=23:20

**Comment by fusang1337** [comment]
![IMG_0936.jpeg](https://s2.loli.net/2023/03/06/ecHviOTG2ymDLZ8.jpg)
![IMG_0935.jpeg](https://s2.loli.net/2023/03/06/Yf6NQjsk2quH54J.jpg)
![IMG_0934.jpeg](https://s2.loli.net/2023/03/06/pmGTY7W9JdgAD2K.jpg)
![IMG_0932.jpeg](https://s2.loli.net/2023/03/06/mPBtFLwK5I4VQNe.jpg)

**Comment by quarkape** [comment]
看起来也是盛卡恩系统，我大概看了一下请求，应该可以用。不过你们这个预约应该是要内网？我ping不同你们这个api里面的ip地址。

**Comment by quarkape** [comment]
你看一下README和java代码，注释的还是比较细的。另外你把BASE_URL改成“http://219.231.8.77/api.php”，把SCHOOL改成你学校英文名简称，SCHOOL_NAME改成安徽建筑大学。另外你最开始给的“http://219.231.8.77/web/area?area=21&segment=156122&day=2023-03-06&startTime=09:40&endTime=23:20”应该是用来获取座位信息的，这个请求里面你不用加上segement参数，其他参数不变，就能改抓取到id为21的区域的座位信息。其他应该没差别了。

**Comment by quarkape** [comment]
不过你这个有个问题是，只能内网访问的话，就不好部署到外网的服务器上面了，因为只能内网访问。除非你有一台学校内网的服务器。

**Comment by fusang1337** [comment]
> 

禁ping了 内网也ping不通 但是可以正常访问

**Comment by quarkape** [comment]
还真是禁ping了，我请求你们的api能正常请求但是提示访问异常，不清楚具体原因。你把BASE_URL改成http://219.231.8.121/api.php，在test.java里面把login()执行一下打印一下结果，如果可以的话应该就没问题了

**Comment by fusang1337** [comment]
感谢

**Comment by quarkape** [comment]
我已收到您的信件，顺颂时祺。
